admin_app:
    resource: "@AdminAppBundle/Resources/config/routing.yml"
    prefix:   /

urban_calendar:
    resource: "@UrbanCalendarBundle/Resources/config/routing.yml"
    prefix:   /

urban_blog:
    resource: "@UrbanTimelineBundle/Resources/config/routing.yml"
    prefix:   /